export const ERROR_CODES = {
  VALIDATION:    'VALIDATION_ERROR',
  NOT_FOUND:     'NOT_FOUND',
  UNAUTHORIZED:  'UNAUTHORIZED',
  FORBIDDEN:     'FORBIDDEN',
  SERVER_ERROR:  'SERVER_ERROR',
  CONFLICT:      'CONFLICT',
} as const;