import {
  ActivitySquare,
  BarChart2,
  CheckSquare,
  ClipboardList,
  DollarSign,
  FileText,
  FolderKanban,
  GitBranch,
  LayoutDashboard,
  Ruler,
  ShieldCheck,
  UserCheck,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const RESOURCE_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  workflows: GitBranch,
  approvals: CheckSquare,
  documents: FileText,
  employees: Users,
  attendance: UserCheck,
  payroll: DollarSign,
  budget: BarChart2,
  "payroll-review": ClipboardList,
  "impact-review": ActivitySquare,
  designs: Ruler,
  proposals: FileText,
  progress: BarChart2,
  requirements: ClipboardList,
  issues: ActivitySquare,
  tasks: CheckSquare,
  users: Users,
  "audit-logs": ShieldCheck,
  monitoring: ActivitySquare,
  "ai-insights": ActivitySquare,
  reports: BarChart2,
  resources: Wrench,
};
