import {
  ActivitySquare,
  BarChart2,
  Bell,
  BookOpen,
  CheckSquare,
  ClipboardList,
  DollarSign,
  FileText,
  FolderKanban,
  GitBranch,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Receipt,
  Ruler,
  ShieldAlert,
  ShieldCheck,
  UserCheck,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const RESOURCE_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  workflows: GitBranch,
  approvals: CheckSquare,
  documents: FileText,
  employees: Users,
  attendance: UserCheck,
  payroll: DollarSign,
  budget: BarChart2,
  "payroll-review": ClipboardList,
  expenses: Receipt,
  "impact-review": ActivitySquare,
  designs: Ruler,
  proposals: FileText,
  progress: BarChart2,
  requirements: ClipboardList,
  issues: ActivitySquare,
  tasks: CheckSquare,
  users: Users,
  "audit-logs": ShieldCheck,
  monitoring: ActivitySquare,
  "ai-insights": ActivitySquare,
  reports: BarChart2,
  resources: Wrench,
  "architect-projects": FolderKanban,
  revisions: GitBranch,
  reviews: CheckSquare,
  "architect-documents": BookOpen,
  blueprints: Layers,
  "admin-projects": FolderKanban,
  "admin-workflows": GitBranch,
  "admin-documents": FileText,
  "admin-activity-logs": ShieldCheck,
  "admin-security": ShieldAlert,
  "admin-notifications": Bell,
  "admin-roles-permissions": UserCheck,
  "admin-workflow-configuration": GitBranch,
  "admin-approval-hierarchy": CheckSquare,
  "admin-support": LifeBuoy,
  "consultant-proposals": FileText,
  "consultant-designs": Ruler,
  "consultant-projects": FolderKanban,
  "advisory-docs": BookOpen,
  "owner-portfolio": FolderKanban,
  "owner-proposals": FileText,
  "owner-audit-trail": ShieldCheck,
  "owner-oversight": ActivitySquare,
  "it-designer-users": Users,
  "it-designer-proposals": FileText,
  "it-designer-roles-permissions": UserCheck,
  "it-designer-activity-logs": ShieldCheck,
  "it-designer-security": ShieldAlert,
  "it-designer-support": LifeBuoy,
};
