export const ROLE_RESOURCE_ACCESS: Record<string, string[]> = {
  super_admin: ["dashboard", "users", "audit-logs", "monitoring", "reports", "ai-insights"],
  admin: ["dashboard", "users", "monitoring", "reports"],
  owner: [
    "dashboard",
    "users",
    "audit-logs",
    "monitoring",
    "reports",
    "ai-insights",
  ],
  it_designer: ["dashboard", "users", "monitoring", "reports"],
  project_manager: [
    "dashboard",
    "projects",
    "workflows",
    "approvals",
    "documents",
    "ai-insights",
    "resources",
    "reports",
  ],
  human_resources: [
    "dashboard",
    "employees",
    "attendance",
    "payroll",
    "reports",
  ],
  finance_manager: [
    "dashboard",
    "budget",
    "payroll-review",
    "expenses",
    "approvals",
    "impact-review",
    "ai-insights",
    "reports",
  ],
  architect: [
    "dashboard",
    "architect-projects",
    "designs",
    "proposals",
    "revisions",
    "reviews",
    "blueprints",
    "architect-documents",
    "ai-insights",
  ],
  engineer: [
    "dashboard",
    "progress",
    "requirements",
    "issues",
    "projects",
    "ai-insights",
  ],
  site_personnel: ["dashboard", "attendance", "tasks", "documents", "issues"],
  consultant: [
    "dashboard",
    "proposals",
    "documents",
    "approvals",
    "projects",
    "ai-insights",
  ],
};
