export const ROLE_RESOURCE_ACCESS: Record<string, string[]> = {
  admin: [
    "dashboard",
    "admin-projects",
    "admin-workflows",
    "admin-documents",
    "admin-activity-logs",
    "admin-security",
    "admin-notifications",
    "admin-roles-permissions",
    "admin-workflow-configuration",
    "admin-approval-hierarchy",
    "admin-support",
  ],
  owner: [
    "dashboard",
    "owner-portfolio",
    "owner-proposals",
    "owner-audit-trail",
    "owner-oversight",
    "owner-account-recovery",
    "reports",
    "ai-insights",
  ],
  it_designer: [
    "dashboard",
    "it-designer-users",
    "it-designer-proposals",
    // Absorbed from the legacy platform-admin role, since renamed IT-Designer.
    "admin-projects",
    "admin-workflows",
    "admin-documents",
    "admin-workflow-configuration",
    "admin-approval-hierarchy",
    "it-designer-roles-permissions",
    "it-designer-activity-logs",
    "it-designer-security",
    "it-designer-support",
  ],
  project_manager: [
    "dashboard",
    "projects",
    "workflows",
    "approvals",
    "tasks",
    "documents",
    "ai-insights",
    "resources",
    "reports",
  ],
  human_resources: [
    "dashboard",
    "employees",
    "attendance",
    "payroll",
    "workforce-reports",
    "approvals",
    "reports",
  ],
  finance_manager: [
    "dashboard",
    "budget",
    "payroll-review",
    "expenses",
    "approvals",
    "impact-review",
    "ai-insights",
    "reports",
  ],
  architect: [
    "dashboard",
    "architect-projects",
    "designs",
    "proposals",
    // Architect owns a stage in both the Design Proposal Approval and Public
    // works compliance templates, so it needs the shared approvals screen to
    // act on them — and to start them.
    "approvals",
    "revisions",
    "reviews",
    "blueprints",
    "architect-documents",
    "ai-insights",
  ],
  engineer: [
    "dashboard",
    "progress",
    "requirements",
    "approvals",
    "issues",
    "projects",
    "ai-insights",
  ],
  site_personnel: ["dashboard", "attendance", "tasks", "requirements", "documents", "issues"],
  consultant: [
    "dashboard",
    // Consultant's review screen, not the Architect authoring page the
    // generic "proposals" resource points at. Now also carries the workflow
    // decisions that used to need the separate "approvals" resource (see
    // consultant-proposals.tsx's "Workflow approvals" tab) — deliberately
    // absent here so a direct hit on /approvals doesn't leave a second,
    // unmerged path back into the same decisions.
    "consultant-proposals",
    "consultant-designs",
    "advisory-docs",
    "consultant-projects",
    "ai-insights",
  ],
};
