export const ROLE_RESOURCE_ACCESS: Record<string, string[]> = {
  super_admin: [
    "dashboard",
    "admin-projects",
    "admin-workflows",
    "admin-documents",
    "admin-activity-logs",
    "admin-security",
    "admin-notifications",
    "admin-roles-permissions",
    "admin-workflow-configuration",
    "admin-approval-hierarchy",
    "admin-support",
  ],
  admin: [
    "dashboard",
    "admin-projects",
    "admin-workflows",
    "admin-documents",
    "admin-activity-logs",
    "admin-security",
    "admin-notifications",
    "admin-roles-permissions",
    "admin-workflow-configuration",
    "admin-approval-hierarchy",
    "admin-support",
  ],
  owner: [
    "dashboard",
    "owner-portfolio",
    "owner-audit-trail",
    "owner-oversight",
    "reports",
    "ai-insights",
  ],
  it_designer: [
    "dashboard",
    "it-designer-users",
    "it-designer-roles-permissions",
    "it-designer-activity-logs",
    "it-designer-security",
    "it-designer-support",
  ],
  project_manager: [
    "dashboard",
    "projects",
    "workflows",
    "approvals",
    "tasks",
    "documents",
    "ai-insights",
    "resources",
    "reports",
  ],
  human_resources: [
    "dashboard",
    "employees",
    "attendance",
    "payroll",
    "workforce-reports",
    "approvals",
    "reports",
  ],
  finance_manager: [
    "dashboard",
    "budget",
    "payroll-review",
    "expenses",
    "approvals",
    "impact-review",
    "ai-insights",
    "reports",
  ],
  architect: [
    "dashboard",
    "architect-projects",
    "designs",
    "proposals",
    "revisions",
    "reviews",
    "blueprints",
    "architect-documents",
    "ai-insights",
  ],
  engineer: [
    "dashboard",
    "progress",
    "requirements",
    "approvals",
    "issues",
    "projects",
    "ai-insights",
  ],
  site_personnel: ["dashboard", "attendance", "tasks", "requirements", "documents", "issues"],
  consultant: [
    "dashboard",
    "proposals",
    "advisory-docs",
    "approvals",
    "projects",
    "ai-insights",
  ],
};
