import { PageHeader } from "@/components/refine-ui/views/page-header";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { SectionCard } from "@/components/ui/section-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { useDesignDetail } from "@/features/designs/hooks/useDesignDetail";
import { ChevronLeft, Sparkles, Trash2 } from "lucide-react";
import { useState } from "react";
import { useNavigate, useParams } from "react-router";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";

export default function ArchitectDesignDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const c = useDesignDetail(id!);
  const [confirmDelete, setConfirmDelete] = useState(false);

  if (c.loading) {
    return (
      <div className="p-8 text-sm text-muted-foreground">Loading design…</div>
    );
  }

  if (c.error || !c.design) {
    return (
      <div className="flex-1 space-y-4 p-4 md:p-8">
        <Button
          variant="ghost"
          size="sm"
          className="rounded-xl"
          onClick={() => navigate("/designs")}
        >
          <ChevronLeft className="mr-1 h-4 w-4" /> All designs
        </Button>
        <div className="rounded-2xl border border-dashed p-10 text-center text-sm text-muted-foreground">
          {c.error ?? "Design not found."}
        </div>
      </div>
    );
  }

  const d = c.design;

  const handleDelete = async () => {
    const ok = await c.remove();
    if (ok) navigate("/designs");
  };

  return (
    <div className="flex-1 space-y-6 p-4 md:p-8">
      <Button
        variant="ghost"
        size="sm"
        className="-mb-2 rounded-xl"
        onClick={() => navigate("/designs")}
      >
        <ChevronLeft className="mr-1 h-4 w-4" /> All designs
      </Button>

      <PageHeader
        title={d.name}
        description={`${d.code} · ${d.projectCode}`}
        actions={
          <>
            <Button
              size="sm"
              variant="outline"
              className="rounded-xl text-destructive"
              onClick={() => setConfirmDelete(true)}
            >
              <Trash2 className="mr-1 h-3.5 w-3.5" /> Delete
            </Button>
            <StatusBadge status={d.status} />
          </>
        }
      />

      <div className="grid gap-4 lg:grid-cols-3">
        <SectionCard title="Design details" className="lg:col-span-2">
          <dl className="grid gap-4 md:grid-cols-2">
            <Field label="Discipline" value={d.discipline} />
            <Field label="Category" value={d.category} />
            <Field label="Phase" value={d.phase} />
            <Field label="Version" value={`${d.version} · rev ${d.revision}`} />
            <Field label="Lead architect" value={d.leadArchitect} />
            <Field label="Client" value={d.client ?? "—"} />
            <Field label="Building" value={d.building ?? "—"} />
            <Field label="Floor" value={d.floor ?? "—"} />
            <Field label="Zone" value={d.zone ?? "—"} />
            <Field label="Files" value={`${d.fileCount}`} />
          </dl>
          {d.description && (
            <div className="mt-4 border-t border-border/70 pt-4">
              <div className="text-xs uppercase tracking-wider text-muted-foreground">
                Description
              </div>
              <p className="mt-1 text-sm">{d.description}</p>
            </div>
          )}
        </SectionCard>

        <SectionCard
          title="AI analysis"
          subtitle="Advisory only — manually entered, no live model connected"
        >
          <div className="space-y-4">
            <div className="flex items-center gap-2 rounded-xl border border-primary/20 bg-primary/5 p-3 text-xs text-muted-foreground">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              These scores are not yet generated by a live AI pipeline.
            </div>
            <div>
              <div className="flex items-center justify-between text-xs">
                <span>Completeness</span>
                <span className="text-muted-foreground">
                  {d.aiCompleteness}%
                </span>
              </div>
              <Progress value={d.aiCompleteness} className="mt-1 h-1.5" />
            </div>
            <div>
              <div className="flex items-center justify-between text-xs">
                <span>Confidence</span>
                <span className="text-muted-foreground">{d.aiConfidence}%</span>
              </div>
              <Progress value={d.aiConfidence} className="mt-1 h-1.5" />
            </div>
          </div>
        </SectionCard>
      </div>

      <ConfirmDialog
        open={confirmDelete}
        onOpenChange={setConfirmDelete}
        title={`Delete design "${d.name}"?`}
        description="This action cannot be undone."
        confirmLabel="Delete design"
        loading={c.deleting}
        onConfirm={handleDelete}
      />
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wider text-muted-foreground">
        {label}
      </div>
      <div className="text-sm">{value}</div>
    </div>
  );
}

ArchitectDesignDetail.displayName = "ArchitectDesignDetail";
